# This file can be used for thesting the API with a dedicated Visual Studio Code extension.

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "tedi@polito.it",
    "password": "testtest"
}
###

## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###


## Request for round NO logged user
GET http://localhost:3001/api/round/single HTTP/1.1
###

## Request round for logged user
GET http://localhost:3001/api/round/1 HTTP/1.1
###


## Request for history of :id user 
GET http://localhost:3001/api/history/1 HTTP/1.1
###

## Request for history of a match with match_id
GET http://localhost:3001/api/matchHistory/472 HTTP/1.1
###